import{a as M,S as R,i as n}from"./assets/vendor-BclIaOog.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const B="https://pixabay.com/api/",$="52901396-de7aac391364669bcd79cab11",A={key:$,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15};async function h(s,t=1){try{return(await M.get(B,{params:{q:s,page:t,...A}})).data}catch(r){throw r}}const g=document.querySelector(".gallery"),d=document.querySelector(".loader-wrapper"),f=document.querySelector(".load-more"),O=new R(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});function p(s){const t=s.map(r=>{const{webformatURL:i,largeImageURL:e,tags:o,likes:l,views:E,comments:P,downloads:q}=r;return`
      <li class="gallery-item">
        <a class="gallery-link" href="${e}">
          <img class="gallery-image" src="${i}" alt="${o}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${l}</p>
          <p class="info-item"><b>Views</b> ${E}</p>
          <p class="info-item"><b>Comments</b> ${P}</p>
          <p class="info-item"><b>Downloads</b> ${q}</p>
        </div>
      </li>
      `}).join("");g.insertAdjacentHTML("beforeend",t),O.refresh()}function x(){g&&(g.innerHTML="")}function b(){d&&d.classList.add("is-visible")}function L(){d&&d.classList.remove("is-visible")}function w(){f&&f.classList.add("is-visible")}function c(){f&&f.classList.remove("is-visible")}const v=document.querySelector(".form"),D=v.elements["search-text"],y=document.querySelector(".load-more"),S=15;let a=1,m="",u=0;c();v.addEventListener("submit",W);y&&y.addEventListener("click",_);async function W(s){s.preventDefault();const t=D.value.trim();if(!t){n.warning({title:"Warning",message:"Please enter a search query"});return}m=t,a=1,u=0,x(),c(),b();try{const r=await h(m,a),{hits:i,totalHits:e}=r;if(u=e,!i||i.length===0){n.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"});return}p(i),n.success({title:"Success",message:`Found ${u} images.`}),a*S<u?w():(c(),a===1&&n.info({title:"End",message:"We're sorry, but you've reached the end of search results."}))}catch(r){console.error(r),n.error({title:"Error",message:"Something went wrong when fetching images. Please try again later."})}finally{L()}}async function _(){if(m){a+=1,b(),c();try{const s=await h(m,a),{hits:t}=s;if(!t||t.length===0){n.info({title:"End",message:"We're sorry, but you've reached the end of search results."}),c();return}p(t);const r=document.querySelector(".gallery .gallery-item");if(r){const{height:i}=r.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}a*S<u?w():(c(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results."}))}catch(s){console.error(s),n.error({title:"Error",message:"Something went wrong while loading more images."})}finally{L()}}}
//# sourceMappingURL=index.js.map
